
export const Editor = {
  SET_TARGET: 'SET_TARGET',
  SET_EDITOR_MODE: 'SET_EDITOR_MODE',
  SET_FRAMECHOICES: 'SET_FRAMECHOICES',
  SET_TARGET_AND_SHOW_EDITOR: 'SET_TARGET_AND_SHOW_EDITOR',
  SHOW_EDITOR: 'SHOW_EDITOR',
  HIDE_EDITOR: 'HIDE_EDITOR',
  TOGGLE_EDITOR_DISPLAY: 'TOGGLE_EDITOR_DISPLAY',
  CHANGE_TARGET_CONTENT: 'CHANGE_TARGET_CONTENT',
  CHANGE_TARGET_NAME: 'CHANGE_TARGET_NAME',
  CHANGE_TARGET_FRAME: 'CHANGE_TARGET_FRAME',
};

export const Graph = {
  REFRESH_ONE: 'REFRESH_ONE',
  REFRESH_MULTI: 'REFRESH_MULTI',
};