
export const Editor = {
  REQUEST_FETCH: 'REQUEST_FETCH',
  SET_TARGET: 'SET_TARGET',
  SET_FRAMECHOICES: 'SET_FRAMECHOICES',
  CHANGE_TARGET_CONTENT: 'CHANGE_TARGET_CONTENT',
  CHANGE_TARGET_NAME: 'CHANGE_TARGET_NAME',
  CHANGE_TARGET_FRAME: 'CHANGE_TARGET_FRAME',
};

export const Graph = {
  REFRESH_ONE: 'REFRESH_ONE',
  REFRESH_MULTI: 'REFRESH_MULTI',
};